openshift/cluster-resource-override-admission-operator

- Makefile
A potential fix for the following error in e2e job
```
kubectl apply -f ""./_output"/deploy"
/bin/sh: kubectl: command not found
make: *** [deploy] Error 127
```
> Fix Makefile to point to oc binary in CI

- artifacts/deploy/300_deployment.yaml
Potential fix for the following error 
```
error: unable to recognize "_output/deploy/300_deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
make: *** [deploy] Error 1
```
> Use apps/v1 for Deployment object

- Makefile
Potential fix for the following CI error
```
kubectl -n clusterresourceoverride-operator rollout status -w deployment/clusterresourceoverride-operator
make: kubectl: Command not found
make: *** [e2e] Error 127
```
> Fix Makefile to use KUBECTL env var

- Makefile
Potential fix for the following error
```
kubectl -n clusterresourceoverride-operator rollout status -w deployment/clusterresourceoverride-operator
make: kubectl: Command not found
make: *** [e2e] Error 127
```
> Fix e2e-ci goal in Makefile

- hack/enable-art-dev-env.sh
- images/operator-registry/Dockerfile.registry.ci
- Fix operator registry Dockerfile. The location of the operator registry binaries in 'upstream-registry-builder' have moved, fix the Dockerfile to account for the breaking change.
- Fix hack/enable-art-dev-env script
> Bug 1796987: Fix e2e with olm

- Makefile
In CI it takes longer for olm to deploy the operator, so increase the wait time.
> Bug 1796987: Increase wait time for olm install

- Makefile
- hack/wait-for-deployment.sh
- manifests/4.4/clusterresourceoverride-operator.v4.4.0.clusterserviceversion.yaml
- Add `relatedImages' to the `ClusterServiceVersion` to support
disconnected install.
- Add both the operator and the operand image url
- `wait-for-deployment.sh` should fail if kubectl/oc binary is not
present instead of giving false message of retries.
> Bug 1796987: e2e with olm

- .dockerignore
- artifacts/deploy/200_rbac.yaml
- artifacts/example/test-pod-with-limitranges.yaml
- manifests/4.4/clusterresourceoverride-operator.v4.4.0.clusterserviceversion.yaml
- pkg/asset/rbac.go
- pkg/asset/webhookconfiguration.go
- test/e2e/dynamic_test.go
- test/e2e/e2e_test.go
- test/helper/helper.go
The overridden quantity must be below the namespace Maximum specified via LimitRange object.
Currently the mutating admission webhook overrides a resource above
the namespace maximum and thus fails Pod creation, we see the
following error:
"pods "croe2e-f7c9h" is forbidden: maximum cpu usage per Container is 1, but limit is 2"
Query the Maximum limit for CPU and Memory resource specified in LimitRange and ensure that the overridden resource quantity never exceeds the namespace Maximum.
Add e2e tests:
- Ensure that dynamic client can create if specified object does not exist.
- Ensure that dynamic client can patch an existing object. It should preserve annotations/labels added to the object by cluster admins. It should add new labels/annotations specified.
> Bug 1801850: Overridden quantity must be below namespace Maximum

- manifests/4.6/clusterresourceoverride-operator.v4.6.0.clusterserviceversion.yaml
ART is intended to fill this in downstream; having it here already makes an invalid entry.
It's possible ART tooling could be made to replace this instead of add to it but it would certainly be simpler for us to remove this unless you know it's needed for something in CI.
> CSV: remove relatedImages

- Dockerfile.codegen
- Dockerfile.rhel7
- Makefile
- README.md
- artifacts/deploy/200_rbac.yaml
- images/ci/Dockerfile
- images/operator-registry/Dockerfile.registry.ci
- manifests/4.9/clusterresourceoverride-operator.v4.9.0.clusterserviceversion.yaml
- manifests/4.9/clusterresourceoverride.crd.yaml
- pkg/asset/daemonset.go
- pkg/asset/deployment.go
- pkg/asset/rbac.go
- pkg/asset/webhookconfiguration.go
- pkg/clusterresourceoverride/internal/handlers/deploy.go
- pkg/clusterresourceoverride/internal/handlers/webhook.go
- pkg/ensurer/webhookconfiguration.go
- pkg/secondarywatch/lister.go
- pkg/secondarywatch/start.go
- test/e2e/e2e_test.go
- test/helper/precondition.go
CRD `apiextensions.k8s.io/v1beta1` is being removed in 4.9 and so we must switch our CRD to `apiextensions.k8s.io/v1beta1` or the operator will break.
Conversion done on a 4.8 cluster via 
```
oc get crd clusterresourceoverrides.operator.autoscaling.openshift.io -o yaml
```
then stripping the `conditions` field and all `metadata` fields except `name`.
Also includes @rphillips' updates to other v1beta1 types and updates to base images, etc.
> Bug 1996213: Switch crd from v1beta1 to v1

- manifests/4.9/clusterresourceoverride-operator.v4.9.0.clusterserviceversion.yaml
The OperatorHub currently assumes x86-only for any operators which do
not declare any such labels.  Declaring these explicitly should make the
current status more obvious in the code, and make it easier to correctly
add further architectures when conditions warrant.
> Bug 1987136: Declare supported arches in CSV

- manifests/4.9/clusterresourceoverride-operator.v4.9.0.clusterserviceversion.yaml
The github repository link in the CSV is broken. Fixing it to the correct link.
> fix broken link in the CSV

- pkg/clusterresourceoverride/internal/handlers/deploy.go
This change adds the operand image and version in the daemontSet handler to ensure the mismatch are reconciled correctly.
Fixes https://github.com/openshift/cluster-resource-override-admission-operator/issues/87
> OCPBUGS-6101: Ensure operand image and version mismatch are reconciled

- manifests/stable/clusterresourceoverride-operator.clusterserviceversion.yaml
Add ppc64le arch label to make CRO operator visible in OperatorHub on ppc64le platform.
> add ppc64le arch label to CRO

- manifests/stable/clusterresourceoverride-operator.clusterserviceversion.yaml
This PR adds a label for platform / architecture *s390x* to the operator CSV. See the following Jira issue for reference: https://issues.redhat.com/browse/OCPBUGS-7075
> Added s390x architecture label to operator CSV

- test/e2e/dynamic_test.go
This PR adds the required SecurityContext configuration to the e2e test pod in test/e2e/dynamic_test.go, addressing the warnings reported in issue #102
This PR should be retrofitted to branches release-4.12 and release-4.13 as well.
> Added SecurityContext settings to e2e dynamic test pod

- artifacts/deploy/200_rbac.yaml
- manifests/stable/clusterresourceoverride-operator.clusterserviceversion.yaml
- pkg/asset/apiservice.go
- pkg/asset/daemonset.go
- pkg/asset/rbac.go
- pkg/asset/service.go
- pkg/asset/webhookconfiguration.go
- pkg/clusterresourceoverride/internal/handlers/apiservice.go
- pkg/clusterresourceoverride/internal/handlers/webhook.go
- pkg/clusterresourceoverride/internal/reconciler/reconciler.go
- pkg/operator/run.go
- test/e2e/e2e_test.go
This PR correctly fixes the operator to configure the webhook server as a proper aggregated extension API server. Previously, the webhook was directly calling the CRO server and hence we "required" `system:anonymous` cluster role and role bindings for the server. The extension apiserver now can validate that the user/group retrieved from the headers are authorized to execute the given request.
> OCPBUGS-33577: Fixes webhook configuration to be correctly configured as an extension API server

- artifacts/deploy/200_rbac.yaml
- artifacts/example/deployment-overrides-specified.yaml
- manifests/stable/clusterresourceoverride-operator.clusterserviceversion.yaml
- manifests/stable/clusterresourceoverride.crd.yaml
- pkg/apis/autoscaling/v1/override.go
- pkg/apis/autoscaling/v1/override_types.go
- pkg/asset/deployment.go
- pkg/clusterresourceoverride/controller.go
- pkg/clusterresourceoverride/internal/handlers/deploy.go
- pkg/clusterresourceoverride/internal/handlers/validation.go
- pkg/clusterresourceoverride/internal/reconciler/reconciler.go
- test/e2e/e2e_test.go
- test/helper/helper.go
~~For now only, CRD changes only allow `nodeSelector` to be applied to the deployment in order to influence pod scheduling. Example in `artifacts/example/node-selector-applied.yaml`.~~
~~Also, should the `nodeSelector` (+ `affinity`?) be placed somewhere else that's not in `podResourceOverride.spec`? Maybe in a new field?~~
Converts DaemonSet to Deployment.
Modifies CRD to include `deploymentOverrides` to override `nodeSelector` and `tolerations` for pod specs and `replicas` for deployment spec.
Also adds anti-affinity so that two pods do not schedule on the same node.
> PODAUTO-189: PODAUTO-190:  Run CRO as a deployment and allow admins to scale and control where they run on

- Dockerfile.codegen
- Dockerfile.rhel7
- Makefile
- README.md
- images/ci/Dockerfile
- images/dev/Dockerfile.dev
- images/operator-registry/Dockerfile.registry
- images/operator-registry/Dockerfile.registry.ci
* Did not update `Dockerfile.rhel7` referenced in [productization config](https://github.com/openshift-eng/ocp-build-data/blob/39d776b80aa929c42b98e8c50c25162b97b14e06/images/clusterresourceoverride-operator.yml#L3) because ART does not support it yet.
* Updated Makefile
*  to support other builders/container engines like buildah and podman
* to add undeploy rule
* to add rules for applying CR and test-pod 
* general bug fixes and updates
* Updated images/ci/Dockerfile for consistency on the ci side.
* Updated images/dev/Dockerfile.dev from deprecated centos to ubi9-minimal image
* Updated README.md for better documentation of local development.
> PODAUTO-202: Update ocp/builder images to openshift/release images

- pkg/dynamic/ensurer.go
- If the CRO operand would fail to start for some reason
- CRO operator would keep ensuring its environment so it eventually could hopefully start
- Every time the CRO operator "ensured" the service account, the patch it applied stripped the secrets
- This made openshift-controller-manager make new ones every time 
- This resulted in clusters filling up with secrets :disappointed: 
So what I did here was just add a special case to the dynamic ensure client to avoid the unpleasant behavior. We probably need to do a "tech debt" pass on this at some point, but this fix is simple and very cherry-pickable. 
Fixes: [OCPBUGS-15462](https://issues.redhat.com/browse/OCPBUGS-15462)
> OCPBUGS-15462: re-inject service account secrets in dynamic ensure client to avoid "secret spam" from openshift-controller-manager

- pkg/apis/autoscaling/v1/override.go
- pkg/clusterresourceoverride/internal/handlers/configuration.go
- test/e2e/e2e_test.go
- test/helper/helper.go
Basically just adds the field to the configuration hash.
Only thing that's slightly confusing is that we are hashing the entire override object because of https://github.com/openshift/cluster-resource-override-admission-operator/pull/151, and checking if we need a reconcile based on that hash, but we are only persisting the `podResourceOverride` to the configmap for the operand to consume. I added a comment in the code to take note of this.
> OCPBUGS-44649: Allow clusterresourceoverride-configuration configMap to reconcile on ForceSelinuxRelabel field

- pkg/apis/autoscaling/v1/override.go
- test/e2e/e2e_test.go
- test/helper/helper.go
Cherry-pick of #172 with some fixed merge conflicts.
> OCPBUGS-48690: [release-4.16] Allow clusterresourceoverride-configuration configMap to reconcile on ForceSelinuxRelabel field

- artifacts/deploy/200_rbac.yaml
- manifests/stable/clusterresourceoverride-operator.clusterserviceversion.yaml
- pkg/clusterresourceoverride/internal/handlers/service.go
Fixes: [OCPBUGS-54886](https://issues.redhat.com/browse/OCPBUGS-54886)
Checks if there exists the serving cert secret in the cro namespace. 
If it exists, and doesn't have the service-ca operator annotation, then delete it. It is the old self-signed generated cert that is embedded in a secret that we generated from the operator before 4.17. The service-ca operator will regenerate the secret with the correct annotation and the correct SAN in the cert that is signed by openshift.
If it doesn't exist, just passthrough like normal.
We need to add some rbac to the operator in order to delete the secret.
I tested this using the method in https://github.com/openshift/cluster-resource-override-admission-operator/pull/179
> OCPBUGS-54886: delete old self-signed cert secret if it exists

- artifacts/deploy/200_rbac.yaml
- manifests/stable/clusterresourceoverride-operator.clusterserviceversion.yaml
- pkg/clusterresourceoverride/internal/handlers/apiservice.go
This bug was a result of the APIService not being reachable when deleting a CRO object. This commit just adds the owner reference on the apiservice to the CRO such that if it's deleted, both the service and the APIService will be deleted too and not cause other operators to fail installations.
It looks like I changed some extra stuff in there because I'm making sure the operator patches the APIService object if it already exists in the cluster.
We need to add the delete rule on apiservices because it's required in order to set `ownerReference` on it.
> OCPBUGS-48115: set ownerReference on apiservice to reference cro

- .gitignore
- bundle.Dockerfile
- catalog.Dockerfile
- hack/build-bundle.sh
- hack/build-fbc.sh
- hack/deploy-catalogsource.sh
Adds some scripts and Dockerfiles that help in building local OLM bundles and catalogs.
Here's an example workflow.
If you want to reproduce an upgrade regression bug, you will want to build a bundle containing the version before that bug, and a bundle container some version after it. You first:
1. Checkout the release branch of the version before the bug was introduced.
2. run `./hack/build-bundle.sh` and make sure your environment variables are set to build and push a bundle image (make sure you're logged into podman/docker/whatever and that the image will be public)
3. Checkout the release branch of some version after the bug was introduced.
4. Do part 2 again for this version but with a different tag/pullspec.
5. Run `./hack/build-catalog.sh` with the right env vars, in order to build …
> AUTOSCALE-236: Allow building olm bundles and catalogs for local upgrade testing

- bundle/manifests/clusterresourceoverride-operator.clusterserviceversion.yaml
- bundle/manifests/operator.autoscaling.openshift.io_clusterresourceoverrides.yaml
- bundle/metadata/annotations.yaml
- hack/build-fbc.sh
- hack/generate-bundle.sh
Renames `build-bundle.sh -> generate-bundle.sh` and commits the generated bundle.
We need this because it makes it easier for CI to run operator-sdk upgrade tests by allowing it to consume an existing bundle and promote the bundle image through CI. Reference from this page: https://docs.ci.openshift.org/docs/how-tos/testing-operator-sdk-operators/#operator-upgrade-testing
Bundle was created by doing:
```
$ SKIP_BUILD=true ./hack/generate-bundle.sh
Generating bundle
Generating bundle manifests
...
````
> AUTOSCALE-236: Generate a bundle for CI to consume

- Makefile
- bundle/manifests/clusterresourceoverride-operator.clusterserviceversion.yaml
- manifests/art.yaml
- manifests/clusterresourceoverride-operator.package.yaml
- manifests/stable/clusterresourceoverride-operator.clusterserviceversion.yaml
- manifests/stable/image-references
```bash
$ sed -i 's/4.20/4.21/g' Makefile  manifests/stable/clusterresourceoverride-operator.clusterserviceversion.yaml manifests/stable/image-references manifests/art.yaml manifests/clusterresourceoverride-operator.package.yaml
$ SKIP_BUILD=true ./hack/generate-bundle.sh
```
Note there is no:
-   dockerfile image bumping
-   rebasing
-   deps bumping
as part of this PR. It should be transparent in terms of functionality.
I didn't include the extra commits in https://github.com/openshift/vertical-pod-autoscaler-operator/pull/209 to reduce the amount of bumping we do because those files in this repo are actually needed to be versioned for a local and CI deploy (at least without changing how it works, and that's a unneeded hassle).
> OCPBUGS-61410: Updates for 4.21 to satisfy ART builds
